// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "discussion-forum/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockPostRepositoryInterface is an autogenerated mock type for the PostRepositoryInterface type
type MockPostRepositoryInterface struct {
	mock.Mock
}

type MockPostRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepositoryInterface) EXPECT() *MockPostRepositoryInterface_Expecter {
	return &MockPostRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: req
func (_m *MockPostRepositoryInterface) Create(req *models.CreatePostRequest) (*models.Post, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.CreatePostRequest) (*models.Post, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*models.CreatePostRequest) *models.Post); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.CreatePostRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - req *models.CreatePostRequest
func (_e *MockPostRepositoryInterface_Expecter) Create(req interface{}) *MockPostRepositoryInterface_Create_Call {
	return &MockPostRepositoryInterface_Create_Call{Call: _e.mock.On("Create", req)}
}

func (_c *MockPostRepositoryInterface_Create_Call) Run(run func(req *models.CreatePostRequest)) *MockPostRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CreatePostRequest))
	})
	return _c
}

func (_c *MockPostRepositoryInterface_Create_Call) Return(_a0 *models.Post, _a1 error) *MockPostRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepositoryInterface_Create_Call) RunAndReturn(run func(*models.CreatePostRequest) (*models.Post, error)) *MockPostRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockPostRepositoryInterface) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPostRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockPostRepositoryInterface_Expecter) Delete(id interface{}) *MockPostRepositoryInterface_Delete_Call {
	return &MockPostRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockPostRepositoryInterface_Delete_Call) Run(run func(id int64)) *MockPostRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockPostRepositoryInterface_Delete_Call) Return(_a0 error) *MockPostRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostRepositoryInterface_Delete_Call) RunAndReturn(run func(int64) error) *MockPostRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockPostRepositoryInterface) GetByID(id int64) (*models.Post, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.Post, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.Post); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPostRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockPostRepositoryInterface_Expecter) GetByID(id interface{}) *MockPostRepositoryInterface_GetByID_Call {
	return &MockPostRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockPostRepositoryInterface_GetByID_Call) Run(run func(id int64)) *MockPostRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockPostRepositoryInterface_GetByID_Call) Return(_a0 *models.Post, _a1 error) *MockPostRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepositoryInterface_GetByID_Call) RunAndReturn(run func(int64) (*models.Post, error)) *MockPostRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTopicID provides a mock function with given fields: topicID
func (_m *MockPostRepositoryInterface) GetByTopicID(topicID int64) ([]*models.Post, error) {
	ret := _m.Called(topicID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTopicID")
	}

	var r0 []*models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*models.Post, error)); ok {
		return rf(topicID)
	}
	if rf, ok := ret.Get(0).(func(int64) []*models.Post); ok {
		r0 = rf(topicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(topicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepositoryInterface_GetByTopicID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTopicID'
type MockPostRepositoryInterface_GetByTopicID_Call struct {
	*mock.Call
}

// GetByTopicID is a helper method to define mock.On call
//   - topicID int64
func (_e *MockPostRepositoryInterface_Expecter) GetByTopicID(topicID interface{}) *MockPostRepositoryInterface_GetByTopicID_Call {
	return &MockPostRepositoryInterface_GetByTopicID_Call{Call: _e.mock.On("GetByTopicID", topicID)}
}

func (_c *MockPostRepositoryInterface_GetByTopicID_Call) Run(run func(topicID int64)) *MockPostRepositoryInterface_GetByTopicID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockPostRepositoryInterface_GetByTopicID_Call) Return(_a0 []*models.Post, _a1 error) *MockPostRepositoryInterface_GetByTopicID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepositoryInterface_GetByTopicID_Call) RunAndReturn(run func(int64) ([]*models.Post, error)) *MockPostRepositoryInterface_GetByTopicID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, req
func (_m *MockPostRepositoryInterface) Update(id int64, req *models.UpdatePostRequest) (*models.Post, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, *models.UpdatePostRequest) (*models.Post, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(int64, *models.UpdatePostRequest) *models.Post); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, *models.UpdatePostRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPostRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int64
//   - req *models.UpdatePostRequest
func (_e *MockPostRepositoryInterface_Expecter) Update(id interface{}, req interface{}) *MockPostRepositoryInterface_Update_Call {
	return &MockPostRepositoryInterface_Update_Call{Call: _e.mock.On("Update", id, req)}
}

func (_c *MockPostRepositoryInterface_Update_Call) Run(run func(id int64, req *models.UpdatePostRequest)) *MockPostRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*models.UpdatePostRequest))
	})
	return _c
}

func (_c *MockPostRepositoryInterface_Update_Call) Return(_a0 *models.Post, _a1 error) *MockPostRepositoryInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepositoryInterface_Update_Call) RunAndReturn(run func(int64, *models.UpdatePostRequest) (*models.Post, error)) *MockPostRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostRepositoryInterface creates a new instance of MockPostRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepositoryInterface {
	mock := &MockPostRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
