// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "discussion-forum/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTopicRepositoryInterface is an autogenerated mock type for the TopicRepositoryInterface type
type MockTopicRepositoryInterface struct {
	mock.Mock
}

type MockTopicRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopicRepositoryInterface) EXPECT() *MockTopicRepositoryInterface_Expecter {
	return &MockTopicRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: req
func (_m *MockTopicRepositoryInterface) Create(req *models.CreateTopicRequest) (*models.Topic, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.CreateTopicRequest) (*models.Topic, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*models.CreateTopicRequest) *models.Topic); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.CreateTopicRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTopicRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - req *models.CreateTopicRequest
func (_e *MockTopicRepositoryInterface_Expecter) Create(req interface{}) *MockTopicRepositoryInterface_Create_Call {
	return &MockTopicRepositoryInterface_Create_Call{Call: _e.mock.On("Create", req)}
}

func (_c *MockTopicRepositoryInterface_Create_Call) Run(run func(req *models.CreateTopicRequest)) *MockTopicRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CreateTopicRequest))
	})
	return _c
}

func (_c *MockTopicRepositoryInterface_Create_Call) Return(_a0 *models.Topic, _a1 error) *MockTopicRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepositoryInterface_Create_Call) RunAndReturn(run func(*models.CreateTopicRequest) (*models.Topic, error)) *MockTopicRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockTopicRepositoryInterface) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopicRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTopicRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockTopicRepositoryInterface_Expecter) Delete(id interface{}) *MockTopicRepositoryInterface_Delete_Call {
	return &MockTopicRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockTopicRepositoryInterface_Delete_Call) Run(run func(id int64)) *MockTopicRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTopicRepositoryInterface_Delete_Call) Return(_a0 error) *MockTopicRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopicRepositoryInterface_Delete_Call) RunAndReturn(run func(int64) error) *MockTopicRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockTopicRepositoryInterface) GetAll() ([]*models.Topic, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Topic, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Topic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTopicRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockTopicRepositoryInterface_Expecter) GetAll() *MockTopicRepositoryInterface_GetAll_Call {
	return &MockTopicRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockTopicRepositoryInterface_GetAll_Call) Run(run func()) *MockTopicRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTopicRepositoryInterface_GetAll_Call) Return(_a0 []*models.Topic, _a1 error) *MockTopicRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepositoryInterface_GetAll_Call) RunAndReturn(run func() ([]*models.Topic, error)) *MockTopicRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockTopicRepositoryInterface) GetByID(id int64) (*models.Topic, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.Topic, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.Topic); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTopicRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockTopicRepositoryInterface_Expecter) GetByID(id interface{}) *MockTopicRepositoryInterface_GetByID_Call {
	return &MockTopicRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockTopicRepositoryInterface_GetByID_Call) Run(run func(id int64)) *MockTopicRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTopicRepositoryInterface_GetByID_Call) Return(_a0 *models.Topic, _a1 error) *MockTopicRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepositoryInterface_GetByID_Call) RunAndReturn(run func(int64) (*models.Topic, error)) *MockTopicRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, req
func (_m *MockTopicRepositoryInterface) Update(id int64, req *models.UpdateTopicRequest) (*models.Topic, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, *models.UpdateTopicRequest) (*models.Topic, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(int64, *models.UpdateTopicRequest) *models.Topic); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, *models.UpdateTopicRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTopicRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int64
//   - req *models.UpdateTopicRequest
func (_e *MockTopicRepositoryInterface_Expecter) Update(id interface{}, req interface{}) *MockTopicRepositoryInterface_Update_Call {
	return &MockTopicRepositoryInterface_Update_Call{Call: _e.mock.On("Update", id, req)}
}

func (_c *MockTopicRepositoryInterface_Update_Call) Run(run func(id int64, req *models.UpdateTopicRequest)) *MockTopicRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*models.UpdateTopicRequest))
	})
	return _c
}

func (_c *MockTopicRepositoryInterface_Update_Call) Return(_a0 *models.Topic, _a1 error) *MockTopicRepositoryInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepositoryInterface_Update_Call) RunAndReturn(run func(int64, *models.UpdateTopicRequest) (*models.Topic, error)) *MockTopicRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTopicRepositoryInterface creates a new instance of MockTopicRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopicRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopicRepositoryInterface {
	mock := &MockTopicRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
