// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockVoteRepositoryInterface is an autogenerated mock type for the VoteRepositoryInterface type
type MockVoteRepositoryInterface struct {
	mock.Mock
}

type MockVoteRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoteRepositoryInterface) EXPECT() *MockVoteRepositoryInterface_Expecter {
	return &MockVoteRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: userID, votableID, votableType
func (_m *MockVoteRepositoryInterface) Delete(userID int64, votableID int64, votableType string) error {
	ret := _m.Called(userID, votableID, votableType)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, string) error); ok {
		r0 = rf(userID, votableID, votableType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoteRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVoteRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID int64
//   - votableID int64
//   - votableType string
func (_e *MockVoteRepositoryInterface_Expecter) Delete(userID interface{}, votableID interface{}, votableType interface{}) *MockVoteRepositoryInterface_Delete_Call {
	return &MockVoteRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", userID, votableID, votableType)}
}

func (_c *MockVoteRepositoryInterface_Delete_Call) Run(run func(userID int64, votableID int64, votableType string)) *MockVoteRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockVoteRepositoryInterface_Delete_Call) Return(_a0 error) *MockVoteRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoteRepositoryInterface_Delete_Call) RunAndReturn(run func(int64, int64, string) error) *MockVoteRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetScore provides a mock function with given fields: votableID, votableType
func (_m *MockVoteRepositoryInterface) GetScore(votableID int64, votableType string) (int64, error) {
	ret := _m.Called(votableID, votableType)

	if len(ret) == 0 {
		panic("no return value specified for GetScore")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (int64, error)); ok {
		return rf(votableID, votableType)
	}
	if rf, ok := ret.Get(0).(func(int64, string) int64); ok {
		r0 = rf(votableID, votableType)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(votableID, votableType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVoteRepositoryInterface_GetScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScore'
type MockVoteRepositoryInterface_GetScore_Call struct {
	*mock.Call
}

// GetScore is a helper method to define mock.On call
//   - votableID int64
//   - votableType string
func (_e *MockVoteRepositoryInterface_Expecter) GetScore(votableID interface{}, votableType interface{}) *MockVoteRepositoryInterface_GetScore_Call {
	return &MockVoteRepositoryInterface_GetScore_Call{Call: _e.mock.On("GetScore", votableID, votableType)}
}

func (_c *MockVoteRepositoryInterface_GetScore_Call) Run(run func(votableID int64, votableType string)) *MockVoteRepositoryInterface_GetScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *MockVoteRepositoryInterface_GetScore_Call) Return(_a0 int64, _a1 error) *MockVoteRepositoryInterface_GetScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVoteRepositoryInterface_GetScore_Call) RunAndReturn(run func(int64, string) (int64, error)) *MockVoteRepositoryInterface_GetScore_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: userID, votableID, votableType, value
func (_m *MockVoteRepositoryInterface) Upsert(userID int64, votableID int64, votableType string, value int) error {
	ret := _m.Called(userID, votableID, votableType, value)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64, string, int) error); ok {
		r0 = rf(userID, votableID, votableType, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoteRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockVoteRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - userID int64
//   - votableID int64
//   - votableType string
//   - value int
func (_e *MockVoteRepositoryInterface_Expecter) Upsert(userID interface{}, votableID interface{}, votableType interface{}, value interface{}) *MockVoteRepositoryInterface_Upsert_Call {
	return &MockVoteRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", userID, votableID, votableType, value)}
}

func (_c *MockVoteRepositoryInterface_Upsert_Call) Run(run func(userID int64, votableID int64, votableType string, value int)) *MockVoteRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockVoteRepositoryInterface_Upsert_Call) Return(_a0 error) *MockVoteRepositoryInterface_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoteRepositoryInterface_Upsert_Call) RunAndReturn(run func(int64, int64, string, int) error) *MockVoteRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVoteRepositoryInterface creates a new instance of MockVoteRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoteRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoteRepositoryInterface {
	mock := &MockVoteRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
