// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "discussion-forum/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: req
func (_m *MockUserRepositoryInterface) Create(req *models.CreateUserRequest) (*models.User, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.CreateUserRequest) (*models.User, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*models.CreateUserRequest) *models.User); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.CreateUserRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - req *models.CreateUserRequest
func (_e *MockUserRepositoryInterface_Expecter) Create(req interface{}) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", req)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(req *models.CreateUserRequest)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CreateUserRequest))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(_a0 *models.User, _a1 error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(*models.CreateUserRequest) (*models.User, error)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockUserRepositoryInterface) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockUserRepositoryInterface_Expecter) Delete(id interface{}) *MockUserRepositoryInterface_Delete_Call {
	return &MockUserRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserRepositoryInterface_Delete_Call) Run(run func(id int64)) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Delete_Call) Return(_a0 error) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryInterface_Delete_Call) RunAndReturn(run func(int64) error) *MockUserRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockUserRepositoryInterface) GetAll() ([]*models.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockUserRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockUserRepositoryInterface_Expecter) GetAll() *MockUserRepositoryInterface_GetAll_Call {
	return &MockUserRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockUserRepositoryInterface_GetAll_Call) Run(run func()) *MockUserRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepositoryInterface_GetAll_Call) Return(_a0 []*models.User, _a1 error) *MockUserRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_GetAll_Call) RunAndReturn(run func() ([]*models.User, error)) *MockUserRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockUserRepositoryInterface) GetByID(id int64) (*models.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockUserRepositoryInterface_Expecter) GetByID(id interface{}) *MockUserRepositoryInterface_GetByID_Call {
	return &MockUserRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockUserRepositoryInterface_GetByID_Call) Run(run func(id int64)) *MockUserRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_GetByID_Call) Return(_a0 *models.User, _a1 error) *MockUserRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_GetByID_Call) RunAndReturn(run func(int64) (*models.User, error)) *MockUserRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, req
func (_m *MockUserRepositoryInterface) Update(id int64, req *models.UpdateUserRequest) (*models.User, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, *models.UpdateUserRequest) (*models.User, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(int64, *models.UpdateUserRequest) *models.User); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, *models.UpdateUserRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int64
//   - req *models.UpdateUserRequest
func (_e *MockUserRepositoryInterface_Expecter) Update(id interface{}, req interface{}) *MockUserRepositoryInterface_Update_Call {
	return &MockUserRepositoryInterface_Update_Call{Call: _e.mock.On("Update", id, req)}
}

func (_c *MockUserRepositoryInterface_Update_Call) Run(run func(id int64, req *models.UpdateUserRequest)) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*models.UpdateUserRequest))
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) Return(_a0 *models.User, _a1 error) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryInterface_Update_Call) RunAndReturn(run func(int64, *models.UpdateUserRequest) (*models.User, error)) *MockUserRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
