// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "discussion-forum/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockReportRepositoryInterface is an autogenerated mock type for the ReportRepositoryInterface type
type MockReportRepositoryInterface struct {
	mock.Mock
}

type MockReportRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportRepositoryInterface) EXPECT() *MockReportRepositoryInterface_Expecter {
	return &MockReportRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: reportableID, reportableType, req
func (_m *MockReportRepositoryInterface) Create(reportableID int64, reportableType string, req *models.CreateReportRequest) (*models.Report, error) {
	ret := _m.Called(reportableID, reportableType, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, *models.CreateReportRequest) (*models.Report, error)); ok {
		return rf(reportableID, reportableType, req)
	}
	if rf, ok := ret.Get(0).(func(int64, string, *models.CreateReportRequest) *models.Report); ok {
		r0 = rf(reportableID, reportableType, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string, *models.CreateReportRequest) error); ok {
		r1 = rf(reportableID, reportableType, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReportRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - reportableID int64
//   - reportableType string
//   - req *models.CreateReportRequest
func (_e *MockReportRepositoryInterface_Expecter) Create(reportableID interface{}, reportableType interface{}, req interface{}) *MockReportRepositoryInterface_Create_Call {
	return &MockReportRepositoryInterface_Create_Call{Call: _e.mock.On("Create", reportableID, reportableType, req)}
}

func (_c *MockReportRepositoryInterface_Create_Call) Run(run func(reportableID int64, reportableType string, req *models.CreateReportRequest)) *MockReportRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string), args[2].(*models.CreateReportRequest))
	})
	return _c
}

func (_c *MockReportRepositoryInterface_Create_Call) Return(_a0 *models.Report, _a1 error) *MockReportRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportRepositoryInterface_Create_Call) RunAndReturn(run func(int64, string, *models.CreateReportRequest) (*models.Report, error)) *MockReportRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockReportRepositoryInterface) GetAll() ([]*models.Report, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Report
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Report, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Report); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Report)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockReportRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockReportRepositoryInterface_Expecter) GetAll() *MockReportRepositoryInterface_GetAll_Call {
	return &MockReportRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockReportRepositoryInterface_GetAll_Call) Run(run func()) *MockReportRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportRepositoryInterface_GetAll_Call) Return(_a0 []*models.Report, _a1 error) *MockReportRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportRepositoryInterface_GetAll_Call) RunAndReturn(run func() ([]*models.Report, error)) *MockReportRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockReportRepositoryInterface) GetByID(id int64) (*models.Report, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.Report, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.Report); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockReportRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockReportRepositoryInterface_Expecter) GetByID(id interface{}) *MockReportRepositoryInterface_GetByID_Call {
	return &MockReportRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockReportRepositoryInterface_GetByID_Call) Run(run func(id int64)) *MockReportRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockReportRepositoryInterface_GetByID_Call) Return(_a0 *models.Report, _a1 error) *MockReportRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportRepositoryInterface_GetByID_Call) RunAndReturn(run func(int64) (*models.Report, error)) *MockReportRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: id, req
func (_m *MockReportRepositoryInterface) UpdateStatus(id int64, req *models.UpdateReportRequest) (*models.Report, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *models.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, *models.UpdateReportRequest) (*models.Report, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(int64, *models.UpdateReportRequest) *models.Report); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, *models.UpdateReportRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportRepositoryInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockReportRepositoryInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id int64
//   - req *models.UpdateReportRequest
func (_e *MockReportRepositoryInterface_Expecter) UpdateStatus(id interface{}, req interface{}) *MockReportRepositoryInterface_UpdateStatus_Call {
	return &MockReportRepositoryInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, req)}
}

func (_c *MockReportRepositoryInterface_UpdateStatus_Call) Run(run func(id int64, req *models.UpdateReportRequest)) *MockReportRepositoryInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*models.UpdateReportRequest))
	})
	return _c
}

func (_c *MockReportRepositoryInterface_UpdateStatus_Call) Return(_a0 *models.Report, _a1 error) *MockReportRepositoryInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportRepositoryInterface_UpdateStatus_Call) RunAndReturn(run func(int64, *models.UpdateReportRequest) (*models.Report, error)) *MockReportRepositoryInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportRepositoryInterface creates a new instance of MockReportRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportRepositoryInterface {
	mock := &MockReportRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
